// Validates tonemap.cu against tonemap_reference.py (hable, peak=10, desat=0.5).
// Reference codes generated by: python3 tonemap_reference.py
// nvcc -std=c++17 test_tonemap.cu -o /tmp/test_tonemap && /tmp/test_tonemap
#include <array>
#include <iostream>
#include <vector>
#include "tonemap.cu"

struct Case { int transfer; unsigned short y, cb, cr; int Y, U, V; };

// From tonemap_reference.py (transfer 0=hlg, 1=pq).
static const std::array<Case, 12> REF = {{
    {0, 64, 512, 512, 16, 128, 128}, {0, 500, 512, 512, 104, 128, 127},
    {0, 940, 512, 512, 234, 128, 127}, {0, 700, 400, 700, 107, 124, 150},
    {0, 300, 700, 400, 55, 171, 103}, {0, 843, 512, 512, 210, 127, 127},
    {1, 64, 512, 512, 16, 128, 128}, {1, 500, 512, 512, 131, 127, 126},
    {1, 940, 512, 512, 233, 128, 128}, {1, 700, 400, 700, 103, 128, 130},
    {1, 300, 700, 400, 43, 184, 111}, {1, 843, 512, 512, 233, 128, 128},
}};

int main() {
    const int n = REF.size();
    std::vector<unsigned short> y(n), cb(n), cr(n);
    std::vector<int> tr(n);
    for (int i = 0; i < n; ++i) { y[i] = REF[i].y; cb[i] = REF[i].cb; cr[i] = REF[i].cr; tr[i] = REF[i].transfer; }

    unsigned short *dy, *dcb, *dcr; unsigned char *dY, *dU, *dV;
    cudaMalloc(&dy, n*2); cudaMalloc(&dcb, n*2); cudaMalloc(&dcr, n*2);
    cudaMalloc(&dY, n); cudaMalloc(&dU, n); cudaMalloc(&dV, n);
    cudaMemcpy(dy, y.data(), n*2, cudaMemcpyHostToDevice);
    cudaMemcpy(dcb, cb.data(), n*2, cudaMemcpyHostToDevice);
    cudaMemcpy(dcr, cr.data(), n*2, cudaMemcpyHostToDevice);

    std::vector<unsigned char> Y(n), U(n), V(n);
    int bad = 0;
    // Two launches, one per transfer, since transfer is a scalar kernel arg.
    for (int transfer = 0; transfer <= 1; ++transfer) {
        tonemap_pixels<<<(n+63)/64, 64>>>(dy, dcb, dcr, dY, dU, dV, n, transfer, 10.0f, 4, 1.0f, 0.5f);
        cudaDeviceSynchronize();
        cudaMemcpy(Y.data(), dY, n, cudaMemcpyDeviceToHost);
        cudaMemcpy(U.data(), dU, n, cudaMemcpyDeviceToHost);
        cudaMemcpy(V.data(), dV, n, cudaMemcpyDeviceToHost);
        for (int i = 0; i < n; ++i) {
            if (REF[i].transfer != transfer) continue;
            int dyv = abs((int)Y[i]-REF[i].Y), duv = abs((int)U[i]-REF[i].U), dvv = abs((int)V[i]-REF[i].V);
            if (dyv > 4 || duv > 4 || dvv > 4) {
                std::cerr << "mismatch tr=" << transfer << " in(" << REF[i].y << "," << REF[i].cb << ","
                          << REF[i].cr << ") got(" << (int)Y[i] << "," << (int)U[i] << "," << (int)V[i]
                          << ") want(" << REF[i].Y << "," << REF[i].U << "," << REF[i].V << ")\n";
                ++bad;
            }
        }
    }
    if (bad) { std::cerr << bad << " mismatches\n"; return 1; }
    std::cout << "PASS: tonemap CUDA matches numpy oracle (HLG+PQ, hable) within 4 codes\n";
    return 0;
}
