"""NVIDIA regression: failed replacement transitions must resume live program.

Supply source-0.mp4 and source-1.mp4 generated by frame_codes.py at 60 fps.
The standalone graph downloads only its final output for pixel assertions;
it does not change or require a running demo. Run with a freshly built module.
"""
import argparse
from contextlib import contextmanager
import json
from pathlib import Path
import tempfile
import time

import numpy as np

from avpmixer import MixerGraphBuilder
from pyplumber import AVPlumber
from pyplumber.node import DecVideo, Demux, FilterVideo, ForceFPS, InputRec, Realtime, SourceSwitcher
from frame_codes import read_code


@contextmanager
def recovery_graph(paths):
    avp = AVPlumber()
    errors = []
    avp.on_exception = lambda name, kind, message: errors.append((name, kind, message))
    avp.executeCommandsFromString('hwaccel.init {"name":"recovery_gpu","type":"cuda"}')
    avp.edges.planCapacity('*', 3)
    for index, path in enumerate(paths):
        stages = (
            (InputRec, {'url': path, 'loop': True, 'dst': f'p{index}'}),
            (Demux, {'src': f'p{index}', 'routing': {'v:0': f'v{index}'}}),
            (DecVideo, {'src': f'v{index}', 'dst': f'd{index}',
                        'pixel_format': '?cuda', 'hwaccel': 'recovery_gpu'}),
            (Realtime, {'src': f'd{index}', 'dst': f'r{index}', 'set_pts': True}),
            (ForceFPS, {'src': f'r{index}', 'dst': f'f{index}', 'fps': '60/1'}),
        )
        for stage, (node, config) in enumerate(stages):
            avp.addNode(node({'name': f'input_{index}_{stage}', 'group': 'inputs', **config}))
    avp.addNode(SourceSwitcher({
        'name': 'target_gate', 'group': 'inputs', 'src': ['f1', 'missing_target'],
        'dst': 'target', 'active': 0, 'fallback_when_active_missing': False,
    }))
    mixer = MixerGraphBuilder(avp, name='recovery', canvas=(640, 360), fps=(60, 1),
                              hwaccel='recovery_gpu', defer_output=True)
    layer = {'dst_w': 640, 'dst_h': 360, 'fit': 'contain'}
    for index, edge in enumerate(('f0', 'target')):
        mixer.add_source(f'camera{index}', edge, 'inputs', default_graph='')
        mixer.add_scene(f'full{index}', {f'camera{index}': layer})
    mixer.set_initial_scene('full0')
    output_edge = mixer.build()
    avp.addNode(FilterVideo({'name': 'pixel_readback', 'group': 'readback',
                            'src': output_edge, 'dst': 'pixels',
                            'hwaccel': 'recovery_gpu',
                            # hwdownload binds to one CUDA pool; the two scene
                            # compositors own different pools. Normalize only
                            # this assertion branch before CPU readback.
                            'graph': 'scale_cuda=passthrough=0,hwdownload,format=nv12'}))
    output = avp.getEdge('pixels')

    try:
        avp.group('inputs').startNodes()
        deadline = time.monotonic() + 10
        while not all(avp.getEdge(edge).enqueued_total for edge in ('f0', 'target')):
            assert time.monotonic() < deadline, 'input startup timed out'
            assert not errors, errors
            time.sleep(0.01)
        mixer.start_groups()
        deadline = time.monotonic() + 10
        while not all(avp.node(name).isWorking for name in (
            'recovery_comp_a', 'recovery_comp_b', 'recovery_otm_scene_a',
            'recovery_otm_scene_b', 'recovery_out_sel_transition',
        )):
            assert time.monotonic() < deadline, 'mixer startup timed out'
            assert not errors, errors
            time.sleep(0.01)
        mixer.begin_transition_preheat()
        deadline = time.monotonic() + 10
        while not avp.getEdge('recovery_trans_out').enqueued_total:
            assert time.monotonic() < deadline, 'transition prewarm timed out'
            assert not errors, errors
            time.sleep(0.01)
        mixer.finish_transition_preheat()
        avp.group('readback').startNodes()
        mixer.start_output()
        yield avp, mixer, output, errors
    finally:
        avp.shutdown()


def check_recovery(avp, mixer, output, errors):
    def command(text):
        avp.executeCommandsFromString(text)

    def sample(seconds):
        samples = []
        deadline = time.monotonic() + seconds
        while time.monotonic() < deadline:
            try:
                frame = output.get(50)
            except ValueError as error:
                if str(error) != 'get: timeout':
                    raise
                continue
            assert (frame.width, frame.height) == (640, 360)
            luma = np.frombuffer(frame.data[0], dtype=np.uint8).reshape(360, frame.linesize[0])[:, :640]
            code = read_code(luma)
            if code is not None:
                samples.append(code)
        return samples

    def moving_program(source):
        samples = sample(0.5)
        assert len(samples) >= 10, ('program missing or unreadable', samples)
        assert all(identity == source for identity, _ in samples), ('wrong program', samples)
        assert len({frame for _, frame in samples}) >= 10, ('program frozen', samples)
        return len(samples)

    def interruptible_cut():
        # A future cut stays active while we inject the replacement failure.
        mixer.cut('full1', start_pts_ms=time.monotonic_ns() // 1000000 + 30000)
        sample(0.1)

    results = []
    sample(0.5)
    moving_program(0)

    command('node.object.set target_gate active 1')
    sample(0.3)  # Drain all previously delivered target frames.
    interruptible_cut()
    mixer.fade('full1', duration_sec=0.3)
    sample(2.6)  # Native readiness timeout is two seconds.
    results.append({'failure': 'target_timeout', 'moving_program_frames': moving_program(0)})
    # Recover the source without issuing another take. Program must remain live.
    command('node.object.set target_gate active 0')
    sample(0.3)
    moving_program(0)
    mixer.cut('full1')
    sample(0.5)
    moving_program(1)
    mixer.cut('full0')
    sample(0.5)

    # A bad scene filter fails synchronously after capture, before a worker
    # is scheduled. It must take the same rollback path as a timeout.
    mixer.define_scene('invalid', {'camera1': {'graph': 'null'}})
    interruptible_cut()
    # executeCommandsFromString reports protocol errors on its output stream;
    # the assertion is recovery of live pixels, not a Python exception.
    mixer.fade('invalid', duration_sec=0.3)
    sample(0.3)
    results.append({'failure': 'invalid_scene', 'moving_program_frames': moving_program(0)})

    # Explicit duration bypasses media probing, exercising asynchronous prep
    # failure after the interrupt has already retained the program picture.
    with tempfile.TemporaryDirectory() as directory:
        missing = str(Path(directory) / 'missing-wipe.mov')
        interruptible_cut()
        mixer.wipe('full1', missing, duration_sec=0.5)
        sample(5.7)
        results.append({'failure': 'missing_wipe', 'moving_program_frames': moving_program(0)})

    # Cancelling a failed preparation must not let its old poll undo a take.
    command('node.object.set target_gate active 1')
    sample(0.3)
    interruptible_cut()
    mixer.fade('full1', duration_sec=0.3)
    sample(0.1)
    mixer.cut('full0')
    sample(0.4)
    command('node.object.set target_gate active 0')
    sample(0.3)
    mixer.cut('full1')
    sample(2.5)
    results.append({'failure': 'cancelled_timeout', 'moving_program_frames': moving_program(1)})
    unexpected = [error for error in errors
                  if not (error[0] in ('recovery_wipe_input', 'recovery_wipe')
                          and 'No such file or directory' in error[2])]
    assert not unexpected, unexpected
    print(json.dumps({'passed': results, 'expected_input_errors': errors}), flush=True)


def run(paths):
    with recovery_graph(paths) as graph:
        check_recovery(*graph)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('inputs', nargs=2)
    run(parser.parse_args().inputs)
