#!/usr/bin/env bash
# The replay demo on the Rust core, with Docker Compose: Janus and its browser
# preview in their own containers, the player (Rust avplumber + Python TUI) in
# another, run per session.
#
#   demos/replay-rust/run.sh                         start Janus, make a sample recording if
#                                                    there is none, open the TUI
#   demos/replay-rust/run.sh up                      start Janus and the preview (detached)
#   demos/replay-rust/run.sh down                    stop them
#   demos/replay-rust/run.sh build                   build the player image (and Janus)
#   demos/replay-rust/run.sh sample [seconds] [fps] [WxH]  a testsrc2 clip, transcoded
#                                                    into media/ (default 20 s, 30 fps, 640x360)
#   demos/replay-rust/run.sh transcode <vod> [fps]   convert your own file into media/replay.ts
#   demos/replay-rust/run.sh play [player options]   the TUI (needs media/replay.ts)
#   demos/replay-rust/run.sh exercise                the RUN V2 checks, no TUI
#   demos/replay-rust/run.sh shell
#
# The player uses the GPU when it can: NVDEC decodes and NVENC encodes, and no
# frame ever reaches host memory. REPLAY_GPU picks how the container reaches
# the card — `auto` (default), `toolkit` (the NVIDIA container toolkit),
# `devices` (pass the /dev/nvidia* nodes and the driver libraries by hand, for
# a host without the toolkit) or `off`.
#
# Environment: JANUS_HOST_IP (127.0.0.1; the address your browser reaches),
# JANUS_HTTP_PORT (8088), JANUS_PREVIEW_PORT (8080), JANUS_VIDEO_PORT (5004),
# JANUS_RTP_PORT_RANGE (20000-20100), REPLAY_MEDIA (demos/replay-rust/media),
# REPLAY_GPU, REPLAY_BACKEND (auto/cpu/nvidia, what the player asks for),
# JANUS_BITRATE (4000k; raise it with the picture size).
set -euo pipefail

cd "$(dirname "$0")/../.."
readonly compose_file=demos/replay-rust/compose.yaml
readonly gpu_toolkit_file=demos/replay-rust/compose.gpu.yaml
readonly gpu_devices_file=demos/replay-rust/.compose.gpu-devices.yaml
readonly media="${REPLAY_MEDIA:-${PWD}/demos/replay-rust/media}"
export REPLAY_MEDIA="${media}"

# Whichever GPU wiring this host supports, as a compose override, decided once.
gpu_override=""

has_nvidia_devices() {
    [[ -e /dev/nvidiactl ]]
}

toolkit_works() {
    docker run --rm --gpus all --entrypoint true fedora:42 > /dev/null 2>&1
}

# The driver's own libraries, at the paths they have on this host. The versions
# have to match the running kernel module, so they are the host's files rather
# than anything installed in the image.
driver_libraries() {
    # 64-bit only: Fedora keeps 32-bit copies in /usr/lib, and mounting those
    # over the container's paths would only confuse ldconfig.
    local directories=(/usr/lib64 /usr/lib/x86_64-linux-gnu)
    local pattern directory
    for pattern in libcuda libnvcuvid libnvidia-encode libnvidia-ml \
                   libnvidia-nvvm libnvidia-ptxjitcompiler; do
        for directory in "${directories[@]}"; do
            [[ -d "${directory}" ]] || continue
            find "${directory}" -maxdepth 1 -name "${pattern}.so.*[0-9]" 2>/dev/null |
                grep -E '\.so\.[0-9]+\.[0-9]' | head -1
        done
    done | sort -u
}

# A compose override that hands the container the card without the toolkit:
# the device nodes, the driver libraries and nvidia-smi. The entrypoint runs
# ldconfig over them.
write_devices_override() {
    local libraries
    libraries="$(driver_libraries)"
    if [[ -z "${libraries}" ]]; then
        echo "[replay] no NVIDIA driver libraries found; running on the CPU" >&2
        return 1
    fi
    {
        echo "# Generated by run.sh; GPU access without the NVIDIA container toolkit."
        echo "services:"
        echo "  replay:"
        echo "    devices:"
        local device
        for device in /dev/nvidiactl /dev/nvidia-uvm /dev/nvidia-uvm-tools \
                      /dev/nvidia-modeset /dev/nvidia[0-9]*; do
            [[ -e "${device}" ]] && echo "      - ${device}:${device}"
        done
        echo "    volumes:"
        local library
        while read -r library; do
            echo "      - ${library}:${library}:ro"
        done <<< "${libraries}"
        [[ -x /usr/bin/nvidia-smi ]] && echo "      - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi:ro"
    } > "${gpu_devices_file}"
    return 0
}

choose_gpu() {
    local mode="${REPLAY_GPU:-auto}"
    case "${mode}" in
        off)
            return
            ;;
        toolkit)
            gpu_override="${gpu_toolkit_file}"
            ;;
        devices)
            write_devices_override && gpu_override="${gpu_devices_file}"
            ;;
        auto)
            if ! has_nvidia_devices; then
                return
            fi
            if toolkit_works; then
                gpu_override="${gpu_toolkit_file}"
            elif write_devices_override; then
                gpu_override="${gpu_devices_file}"
                echo "[replay] no NVIDIA container toolkit; passing the card in by hand" >&2
            fi
            ;;
        *)
            echo "REPLAY_GPU must be auto, toolkit, devices or off" >&2
            exit 2
            ;;
    esac
    [[ -n "${gpu_override}" ]] && echo "[replay] GPU wired in through ${gpu_override}" >&2
    return 0
}

compose() {
    docker compose -f "${compose_file}" "$@"
}

# Compose for the player, which is the only service that wants the GPU.
compose_player() {
    if [[ -n "${gpu_override}" ]]; then
        docker compose -f "${compose_file}" -f "${gpu_override}" "$@"
    else
        docker compose -f "${compose_file}" "$@"
    fi
}

services_up() {
    compose up -d --build janus janus-preview
}

# `run` for the player: per session, removed afterwards, media mounted.
player() {
    mkdir -p "${media}"
    compose_player run --rm "$@"
}

command="${1:-}"
shift || true
choose_gpu

case "${command}" in
    up)
        services_up
        ;;
    down)
        compose down
        ;;
    build)
        compose_player build replay
        compose build janus janus-preview
        ;;
    sample)
        player replay sample "$@"
        ;;
    transcode)
        [[ $# -ge 1 ]] || { echo "usage: $0 transcode <vod> [fps]" >&2; exit 2; }
        input="$(realpath "$1")"
        fps="${2:-30}"
        player -v "$(dirname "${input}"):/input:ro,z" replay \
            transcode --input "/input/$(basename "${input}")" --output /media/replay.ts --fps "${fps}" --force
        ;;
    play)
        services_up
        player replay play --recording /media/replay.ts "$@"
        ;;
    exercise)
        services_up
        player replay exercise --recording /media/replay.ts "$@"
        ;;
    shell)
        player replay shell
        ;;
    "")
        services_up
        if [[ ! -f "${media}/replay.ts" ]]; then
            player replay sample
        fi
        echo "Open http://${JANUS_HOST_IP:-127.0.0.1}:${JANUS_PREVIEW_PORT:-8080} in a browser to watch."
        player replay play --recording /media/replay.ts
        ;;
    *)
        sed -n '2,19p' "$0" >&2
        exit 2
        ;;
esac
